pub const KEY_INPUT_ERROR: u8 = 100;

pub const FAILED_TO_TERMINATE_UI_THREAD: u8 = 200;
pub const FAILED_TO_FLUSH_UI_SCREEN: u8 = 201;
pub const FAILED_TO_WRITE_TO_UI_SCREEN: u8 = 202;
pub const FAILED_TO_CREATE_UI_SCREEN: u8 = 203;
pub const COULD_NOT_SEND_TO_UI_THREAD: u8 = 204;