name: build-release
on:
  release:
    types: [published, created, edited]

jobs:
  release-mac-os:
    runs-on: macOS-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v1
      - name: package
        run: make package
      - name: upload
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "sidle_x86_64-apple-darwin.tar.gz"
          asset_name: "sidle_x86_64-apple-darwin.tar.gz"
          tag: ${{ github.ref }}
          overwrite: true

  release-linux-os:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v1
      - name: package
        run: RUST_TARGET=x86_64-unknown-linux-gnu SHA_COMMAND=sha512sum make package
      - name: upload
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "sidle_x86_64-unknown-linux-gnu.tar.gz"
          asset_name: "sidle_x86_64-unknown-linux-gnu.tar.gz"
          tag: ${{ github.ref }}
          overwrite: true
